---
title: "Not recoverable unique calls"
output: html_notebook
---


```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r, results='hide'}
gdc_tbl <- read_tsv(
    '../processed_data/gdc_not_recoverable_unique_variants.tsv.gz',
    col_types = cols(
        .default = col_character(),
        start_position = col_integer(), end_position = col_integer(),
        mc3_t_depth = col_integer(), mc3_t_ref_count = col_integer(), mc3_t_alt_count = col_integer(),
        mc3_n_depth = col_integer(), mc3_n_ref_count = col_integer(), mc3_n_alt_count = col_integer()
    )
)

mc3_tbl <- read_tsv(
    '../processed_data/mc3_not_recoverable_unique_variants.tsv.gz',
    col_types = cols(
        .default = col_character(),
        start_position = col_integer(), end_position = col_integer(),
        mc3_t_depth = col_integer(), mc3_t_ref_count = col_integer(), mc3_t_alt_count = col_integer(),
        mc3_n_depth = col_integer(), mc3_n_ref_count = col_integer(), mc3_n_alt_count = col_integer()
    )
)
```

```{r}
nrow(gdc_tbl)
nrow(mc3_tbl)
```


```{r}
gdc_tbl %>% count(gdc_callers, sort=TRUE)
```

```{r}
mc3_tbl %>% count(mc3_callers, sort=TRUE)
```


### MC3 not recoverable unique calls

```{r}
mc3_tbl %>% filter(str_detect(mc3_callers, 'PINDEL')) %>% nrow
mc3_tbl %>% filter(str_detect(mc3_callers, 'INDELOCATOR')) %>% nrow
mc3_tbl %>% filter(str_detect(mc3_callers, 'PINDEL') | str_detect(mc3_callers, 'INDELOCATOR')) %>% nrow
```

```{r}
mc3_other_than_pindel <- mc3_tbl %>% 
    filter(!str_detect(mc3_callers, 'PINDEL') & !str_detect(mc3_callers, 'INDELOCATOR'))
```

```{r}
mc3_other_than_pindel %>% count(mc3_variant_type)
```

```{r}
mc3_other_than_pindel %>% count(mc3_filter, sort = TRUE)
```

```{r}
mc3_other_than_pindel %>% filter(mc3_filter == 'PASS') %>%
    count(mc3_callers, sort = TRUE)
```

```{r}
mc3_other_than_pindel %>% filter(mc3_filter == 'PASS') %>%
    count(cancer_type, sort = TRUE)
```



### GDC not recoverable unique -- MuTect calls

```{r}
mutect_only_calls <- gdc_tbl %>% filter(gdc_callers == 'mutect')
```

```{r}
mutect_only_calls %>% count(gdc_validation_status)
```

```{r}
mutect_only_calls %>% count(gdc_filter, gdc_gdc_filter, sort = TRUE)
mutect_only_calls %>% filter(str_detect(gdc_gdc_filter, 'wga_pair')) %>% nrow
```

```{r}
mutect_only_calls %>% filter(str_detect(gdc_gdc_filter, 'wga')) %>%
    count(gdc_variant_type)

mutect_only_calls %>% filter((!str_detect(gdc_gdc_filter, 'wga')) | is.na(gdc_gdc_filter)) %>%
    count(gdc_variant_type)
```


