---
title: "MC3 unique calls in overlap"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(RSQLite)
```

Connect to the SQLite database.
```{r, results='hide'}
conn = dbConnect(RSQLite::SQLite(), dbname='../processed_data/all_variants.sqlite')
dbExecute(conn, 'PRAGMA cache_size=-16000000')
dbExecute(conn, 'PRAGMA temp_store=MEMORY')
overlap_tbl <- as.tibble(dbReadTable(conn, 'full_overlap'))
# dbDisconnect(conn)
```

Select the variant calls unique in MC3.
```{r}
mc3_unique_tbl <- overlap_tbl %>% filter(only_in_mc3 == 1)
```


## MC3 unique calls

```{r}
mc3_unique_callers <- mc3_unique_tbl %>% 
    group_by(mc3_callers) %>%
    summarize(n = n()) %>% arrange(-n)
```


```{r}
mc3_unrecoverable_unique_callers <- as.tibble(dbGetQuery(
    conn,
    'WITH mc3_unique_unique AS (
        SELECT * FROM full_overlap 
        WHERE only_in_mc3=1 
          AND rowid NOT IN (SELECT DISTINCT overlap_rowid FROM mc3_recoverable_unique)
     )
     SELECT mc3_callers, count(*) AS n 
     FROM mc3_unique_unique 
     GROUP BY mc3_callers 
     ORDER BY n DESC'
))
```


```{r}
callers_tbl <- mc3_unrecoverable_unique_callers %>%
    rename(unrecoverable_n = n) %>% 
    full_join(mc3_unique_callers, by = "mc3_callers") %>%
    arrange(-n)
callers_tbl
```

```{r}
callers_tbl %>%
    filter(str_detect(mc3_callers, 'PINDEL')) %>%
    summarize(unrecoverable_n = sum(unrecoverable_n, na.rm = TRUE), n = sum(n))
```

```{r}
without_pindel_tbl <- mc3_unique_tbl %>%
    filter(!str_detect(mc3_callers, 'PINDEL')) %>%
    group_by(mc3_filter) %>%
    summarize(without_pindel_n = n()) %>% arrange(-without_pindel_n)

mc3_unique_tbl %>%
    group_by(mc3_filter) %>%
    summarize(n = n()) %>% arrange(-n) %>%
    full_join(without_pindel_tbl, by = "mc3_filter") %>%
    full_join(
        as.tibble(dbGetQuery(
            conn,
            'WITH mc3_unique_unique AS (
                SELECT * FROM full_overlap 
                WHERE only_in_mc3=1 
                  AND rowid NOT IN (SELECT DISTINCT overlap_rowid FROM mc3_recoverable_unique)
             )
             SELECT mc3_filter, count(*) AS unrecoverable_n 
             FROM mc3_unique_unique 
             GROUP BY mc3_filter
             ORDER BY unrecoverable_n DESC'
        )),
        by = "mc3_filter"
    )
```

